# Table of Contents
* [Laptop Price Regression Model](#intro)
* [Importing Libraries and Data](#import)
* [Exploratory Data Analysis](#eda)
* [Normality Test](#stats)
* [Splitting Data](#train_split)
* [Preprocessing Data](#preprocessing)
* [Setting Model](#set)
* [Training Model](#training)
* [Best Results](#compare_results)
* [Finalizing Workflow](#workflow)
* [Fitting the final model](#fit)
* [API (FastAPI)](#api)
* [Interface(Streamlit)](#interface)
* [Automation(Docker)](#auto)
* [Saving Files](#store)
* [Conclusion](#conclusion)

## Machine Predictive Maintenance Classification Model <a class="anchor" id="intro"></a>
Introduction

## Importing Libraries and Data<a id="import"></a>

In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import explained_variance_score,mean_absolute_error,r2_score
from time import time
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import ExtraTreesRegressor
import pickle
import json

# read in all our data
laptop_train = pd.read_csv("./../data/raw/laptops_train.csv")
laptop_test = pd.read_csv("./../data/raw/laptops_test.csv")

# set seed for reproducibility
np.random.seed(0)

In [3]:
frames = [laptop_train,laptop_test]
df = pd.concat(frames)

In [4]:
df.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,11912523.48
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,7993374.48
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,5112900.00
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,22563005.40
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,16037611.20

## Exploratory Data Analysis<a id="eda"></a>

## Preprocessing Data<a id="preprocessing"></a>

In [5]:
# get the number of missing data points per column
missing_values_count = df.isnull().sum()
missing_values_count

Manufacturer                  0
Model Name                    0
Category                      0
Screen Size                   0
Screen                        0
CPU                           0
RAM                           0
 Storage                      0
GPU                           0
Operating System              0
Operating System Version    170
Weight                        0
Price                         0
dtype: int64

In [6]:
df['Operating System Version'].value_counts()

Operating System Version
10      1071
7         45
X          8
10 S       8
Name: count, dtype: int64

In [7]:
df[df['Operating System Version'].isna()].groupby('Operating System').groups

{'Android': [50, 136], 'Chrome OS': [290, 317, 430, 437, 472, 504, 584, 619, 677, 690, 697, 745, 762, 817, 828, 838, 846, 888, 907, 949, 953, 959, 71, 110, 124, 213, 237], 'Linux': [36, 40, 42, 59, 69, 96, 97, 102, 180, 210, 220, 235, 236, 272, 276, 281, 296, 338, 340, 379, 394, 403, 415, 423, 427, 439, 446, 524, 543, 555, 579, 604, 612, 613, 614, 616, 651, 669, 711, 712, 728, 769, 832, 852, 876, 886, 896, 965, 112, 145, 204, 210, 220, 249, 264, 272, 285, 289, 299, 303, 313, 317], 'No OS': [2, 10, 11, 18, 22, 46, 62, 76, 122, 125, 136, 138, 142, 172, 184, 187, 192, 193, 205, 212, 213, 216, 242, 261, 267, 279, 289, 303, 305, 356, 364, 367, 381, 463, 509, 514, 527, 547, 594, 627, 643, 654, 704, 725, 752, 783, 850, 859, 863, 871, 932, 947, 14, 78, 83, 113, 150, 172, 174, 186, 195, 196, 218, 223, 239, 270], 'macOS': [0, 1, 3, 4, 7, 12, 14, 15, 17, 45, 81, 249, 270]}

In [8]:
grouped = df.groupby('Operating System')

for name,group in grouped:
    print(name)
    print(group['Operating System Version'].unique())

Android
[nan]
Chrome OS
[nan]
Linux
[nan]
Mac OS
['X']
No OS
[nan]
Windows
['10' '10 S' '7']
macOS
[nan]

In [9]:
#Drop the Operating System Version because the laptop can just be updated by the user
df = df.drop('Operating System Version', axis=1)

In [10]:
df.columns

Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', ' Storage', 'GPU', 'Operating System', 'Weight', 'Price'],
      dtype='object')

In [11]:
df[['Screen Size','Screen']]

    Screen Size                                      Screen
0         13.3"          IPS Panel Retina Display 2560x1600
1         13.3"                                    1440x900
2         15.6"                           Full HD 1920x1080
3         15.4"          IPS Panel Retina Display 2880x1800
4         13.3"          IPS Panel Retina Display 2560x1600
..          ...                                         ...
320       14.0"   IPS Panel Full HD / Touchscreen 1920x1080
321       13.3"  IPS Panel Quad HD+ / Touchscreen 3200x1800
322       14.0"                                    1366x768
323       15.6"                                    1366x768
324       15.6"                                    1366x768

[1302 rows x 2 columns]

In [12]:
#Data Preprocessing
#Course of Action:
#Manufacturer         Target Encoding
#Model Name           Split on the () into two columns- Target Encoding
#Category             One Hot Encoding
#Screen Size          Convert to float and scale (units is inches)
#Screen               Split into new features - screen type, screen quality, HD(Binary), Touchscreen(Binary)
#CPU                  Split into new features - Brand, Model Number, Speed
#RAM                  Remove "GB" and scale
#Storage              Convert to Total Storage column and scale
#GPU                  Split into new features - Brand, Model Number, Speed
#Operating System     One Hot Encoding (macOS = MacOS)
#Weight               Convert to lbs and scale (4s = 4.04 typo)
#Price                Convert to USD

In [13]:
#Treat Manufacturer as an nominal variable
df['Manufacturer'].unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [14]:
# gives a tuple of column name and series
# for each column in the dataframe
for (columnName, columnData) in df.items():
    print('Column Name : ', columnName)
    print('Column Contents : ', columnData.unique())

Column Name :  Manufacturer
Column Contents :  ['Apple' 'HP' 'Acer' 'Asus' 'Dell' 'Lenovo' 'Chuwi' 'MSI' 'Microsoft'
 'Toshiba' 'Huawei' 'Xiaomi' 'Vero' 'Razer' 'Mediacom' 'Samsung' 'Google'
 'Fujitsu' 'LG']
Column Name :  Model Name
Column Contents :  ['MacBook Pro' 'Macbook Air' '250 G6' 'Aspire 3' 'ZenBook UX430UN'
 'Swift 3' 'Inspiron 3567' 'MacBook 12"' 'IdeaPad 320-15IKB' 'XPS 13'
 'Vivobook E200HA' 'Legion Y520-15IKBN' '255 G6' 'Inspiron 5379'
 '15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)' 'MacBook Air' 'Inspiron 5570'
 'Latitude 5590' 'ProBook 470' 'LapBook 15.6"'
 'E402WA-GA010T (E2-6110/2GB/32GB/W10)'
 '17-ak001nv (A6-9220/4GB/500GB/Radeon' 'IdeaPad 120S-14IAP'
 'Inspiron 5770' 'ProBook 450' 'X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)'
 'Inspiron 7577' 'X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce'
 'Aspire A515-51G' 'Inspiron 7773' 'IdeaPad 320-15ISK' 'Rog Strix'
 'X751NV-TY001T (N4200/4GB/1TB/GeForce' 'Yoga Book' 'ProBook 430'
 'Inspiron 3576' '15-bs002nv (i3-6006U/4GB/128GB/FHD/W10)' 'VivoBook Max'
 'GS73VR 7RG' 'X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux)' 'Vostro 5471'
 'IdeaPad 520S-14IKB' 'UX410UA-GV350T (i5-8250U/8GB/256GB/FHD/W10)'
 'ZenBook Pro' 'Stream 14-AX040wm' 'V310-15ISK (i5-7200U/4GB/1TB/FHD/W10)'
 'FX753VE-GC093 (i7-7700HQ/12GB/1TB/GeForce' 'Surface Laptop'
 'Inspiron 5370' 'GL72M 7RDX' 'Aspire E5-475'
 'FX503VD-E4022T (i7-7700HQ/8GB/1TB/GeForce' 'IdeaPad 320-15IKBN'
 'Aspire A515-51G-32MX' 'ProBook 440' 'IdeaPad 320-15AST'
 'Pavilion 15-CK000nv' 'FX503VM-E4007T (i7-7700HQ/16GB/1TB'
 'FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon' 'Aspire 5' 'Probook 430'
 'Zenbook UX430UA' 'Spin 5' 'X541UV-DM1439T (i3-7100U/6GB/256GB/GeForce'
 'Omen 15-ce007nv' '15-bs017nv (i7-7500U/8GB/256GB/Radeon'
 '15-bw000nv (E2-9000e/4GB/500GB/Radeon' 'Envy 13-ad009n'
 'Pavilion 14-BK001nv' 'Ideapad 310-15ISK'
 'UX430UQ-GV209R (i7-7500U/8GB/256GB/GeForce' 'GP62M 7REX' 'Thinkpad T470'
 'VivoBook S15' 'ThinkPad Yoga' 'Probook 440' 'Spectre x360'
 'Inspiron 7570' 'X705UV-BX074T (i3-6006U/4GB/1TB/GeForce' 'Spin 3'
 'GS63VR 7RG' 'Probook 470' 'E402WA-GA007T (E2-6110/4GB/64GB/W10'
 'Inspiron 5567' 'Aspire A515-51G-37JS'
 '15-BS078nr (i7-7500U/8GB/1TB/W10)' 'V110-15IAP (N3350/4GB/1TB/No'
 'FX753VD-GC086T (i5-7300HQ/8GB/1TB' 'Envy 13-AD007nv' 'ThinkPad E480'
 'Satellite Pro' 'ZenBook UX430UA' 'EliteBook Folio'
 'X541NA (N3350/4GB/1TB/FHD/W10)' 'GE72MVR 7RG' 'Aspire A315-51'
 'Inspiron 5577' 'Inspiron 7567' 'V110-15IKB (i5-7200U/4GB/128GB/W10)'
 'GE73VR 7RE' 'EliteBook 840' '15-BS103nv (i5-8250U/6GB/256GB/Radeon'
 'Yoga 520-14IKB' 'ZenBook Flip' 'Inspiron 5579'
 'X555BP-XX180T (A9-9420/4GB/1TB/Radeon' 'Aspire A517-51G'
 'Aspire A315-31' 'GE63VR 7RE' 'MateBook X'
 '17-bs001nv (i5-7200U/6GB/2TB/Radeon' 'GT80S 6QF-074US'
 'V310-15IKB (i5-7200U/8GB/1TB' 'Yoga 920-13IKB' 'Mi Notebook' 'XPS 15'
 'Swift 7' 'Thinkpad Yoga' 'K147 (N3350/4GB/32GB/FHD/W10)'
 'IdeaPad 320-17IKBR' 'Blade Pro' 'Omen 17-W295'
 'V110-15ISK (i5-6200U/4GB/128GB/W10)' 'Aspire E5-576G'
 'Legion Y720-15IKB' 'Precision 7520' 'Aspire 7' 'ROG GL703VD-GC028T'
 '15-bs018nq (i3-6006U/4GB/500GB/FHD/No' 'IdeaPad 320-17IKB'
 'Latitude 5490' 'Portege Z30-C-16L' 'Alienware 17'
 'Vivobook X541UV-DM1217T' 'K756UX-T4340T (i5-7200U/8GB/500GB' 'ZBook 15u'
 'Pro P2540UA-XO0198T' '15-rb013nv (E2-9000e/4GB/500GB/W10)' 'Vostro 5468'
 'Aspire R7' 'X555QG-DM242T (A10-9620P/4GB/1TB' 'ROG G703VI-E5062T'
 'Nitro AN515-51' 'VivoBook Pro' 'F756UX-T4201D (i7-7500U/8GB/128GB'
 'Yoga 910-13IKB' '15-bs015dx (i5-7200U/8GB/1TB/W10)' 'Rog G701VIK-BA060T'
 'ROG G752VSK-GC493T' 'X505BP-BR019T (A9-9420/4GB/1TB/Radeon'
 'Vostro 5370' '15-BW094nd (A6-9220/8GB/128GB/W10)' 'Envy 17-U275cl'
 'GT73EVR 7RE' 'Yoga 720-15IKB' 'Vostro 3568'
 'V330-15IKB (i7-8550U/8GB/256GB/FHD/W10)' 'ThinkPad X1'
 'IdeaPad 320-17ISK' 'Ideapad 320-15IKBN'
 'SP315-51 (i7-7500U/12GB/1TB/FHD/W10)' 'Thinkpad T570'
 'Chromebook C910-C2ST' 'FX753VD-GC071T (i7-7700HQ/8GB/1TB/GeForce'
 '17-BS037cl (i3-6006U/8GB/1TB/W10)'
 'V330-15IKB (i5-8250U/8GB/256GB/FHD/W10)' 'Aspire A715-71G'
 'Precision 7720' 'IdeaPad 310-15ABR' 'ZenBook UX530UQ-PRO' 'VivoBook S14'
 'Rog GL702VS-GC095T' 'GL553VE-FY082T (i7-7700HQ/8GB/1TB'
 'IdeaPad 320-15IAP' 'EliteBook x360' 'IdeaPad 720S-13IKB' 'GE63VR 7RF'
 'ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)' 'VivoBook Flip' 'ThinkPad 13'
 'ProBook 640' 'TravelMate B' 'Elitebook 840' 'ZenBook UX410UA-GV183T'
 'Aspire E5-575' 'Elitebook 820' 'GL72M 7REX'
 'UX510UX-CN269T (i7-7500U/8GB/256GB'
 'V310-15ISK (i3-6006U/4GB/1TB/FHD/W10)'
 'FX553VD-FY647T (i7-7700HQ/8GB/256GB/GeForce' 'Elitebook 850'
 'X541NA (N3350/4GB/1TB/Linux)' 'Inspiron 3552' 'IdeaPad 320-15ABR'
 'Stream 14-AX001nv' 'GP72MVR 7RFX' 'Zbook 15' 'Tecra A50-C-21G'
 'Latitude 7480' 'Zenbook UX410UA-GV027T' '15-AY023na (N3710/8GB/2TB/W10)'
 'Elitebook 1040' 'IdeaPad 110-17ACL'
 '15-bw003nv (A9-Series-9420/4GB/256GB/FHD/W10)' 'Yoga 11e'
 'VivoBook E403NA' 'Omen 17-w212nv'
 'V310-15ISK (i3-6006U/4GB/128GB/FHD/No' 'ROG Strix' 'IdeaPad 720S-14IKB'
 'Zenbook Flip' 'Thinkpad X1' 'Ideapad 510S-13IKB' 'Precision 3510'
 'Precision 5520' 'Rog GL753VD-GC042T' 'Rog GL753VE-GC070T'
 'Leopard GP72M' '15-BW004nv (A9-9420/4GB/256GB/Radeon' 'ThinkPad E580'
 'ThinkPad L470' 'Precision M5520' 'FX753VD-GC461T (i7-7700HQ/16GB/1TB'
 'GE73VR 7RF' 'Zenbook 3' 'Portege Z30-C-16P' 'Lenovo IdeaPad'
 'ThinkPad P51' 'Thinkpad T470p' '15-BS028nv (i3-6006U/4GB/1TB/Radeon'
 'Latitude 3380' 'EliteBook 1040' 'LapBook 12.3' 'ProBook 650'
 'X542UQ-DM117 (i3-7100U/8GB/1TB/GeForce' 'Latitude 5480' 'Omen 17-w207nv'
 'FlexBook Edge' 'Chromebook 3' 'Thinkpad 13' 'IdeaPad 320s-14IKB'
 'Thinkpad P51' '15-ra044nv (N3060/4GB/500GB/W10)' 'Pixelbook (Core'
 'ThinkPad T470s' 'ThinkPad X270' 'Omen 15-AX205na' 'Aspire ES1-572'
 'Precision 3520' 'GV62 7RD-1686NL' '15-bs024nv (i5-7200U/8GB/128GB/W10)'
 'ThinkPad T470' 'Inspiron 3168' '17-BS092ND (i3-6006U/8GB/256GB/W10)'
 'Pro P2540UA-AB51' 'IdeaPad 510s-14IKB'
 'X541NA-PD1003Y (N4200/4GB/500GB/W10)' 'Omen 17-an006nv' 'Thinkpad T460s'
 'Latitude 7390' 'Latitude E5470' 'Portege X30-D-10J' 'Lapbook 15,6'
 'ThinkPad E570' 'Thinkpad X270' 'Zenbook UX390UA' 'Thinkpad E570'
 'Portege X30-D-10L' 'Rog G752VL-UH71T' 'Thinkpad X260'
 'Ideapad 520-15IKBR' 'ThinkPad L570' 'VivoBook E201NA'
 '15-BS026nv (i5-7200U/8GB/256GB/Radeon' 'IdeaPad 320-14IAP'
 'Chromebook N23' 'ZenBook UX510UX-CN211T' 'Aspire A515-51G-59QF'
 'Envy 13-AB002nv' 'Vostro 5568' 'VivoBook E12'
 '15-bs190od (i5-8250U/4GB/1TB/W10)' 'ROG Zephyrus' 'Probook 450'
 'FX753VE-GC155T (i7-7700HQ/16GB/1TB' 'Spectre X360' 'Latitude 5580'
 'Zenbook UX510UW-FI095T' 'SmartBook Edge' 'Omen 15-ce006nv'
 'Thinkpad E470' 'Envy 13-AB020nr' 'VivoBook X540YA-XX519T'
 'ThinkPad E470' 'V310-15ISK (i5-6200U/4GB/1TB/FHD/No' 'ThinkPad T570'
 '17-X047na (i3-6006U/8GB/1TB/W10)' 'A541NA-GO342 (N3350/4GB/500GB/Linux)'
 'SmartBook 130' '15-bw007nv (A10-9620P/6GB/128GB/Radeon' 'Spin SP111-31'
 'V330-15IKB (i3-7130U/4GB/128GB/FHD/W10)' 'EliteBook 1030' 'Thinkpad P71'
 'FX553VD-DM627T (i5-7300HQ/8GB/1TB' 'Lifebook A557' 'ZBook 17'
 '14-am079na (N3710/8GB/2TB/W10)' '15-cd005nv (A9-9420/6GB/256GB/Radeon'
 'V330-15IKB (i5-8250U/4GB/500GB/FHD/W10)' 'SmartBook 141'
 'Tecra X40-D-10H' 'IdeaPad Y910-17ISK' 'GT73VR Titan' 'Chromebook 11'
 'GT80S 6QE' 'Omen 17-AN010nv' 'Ideapad 320-15IKBR'
 'TP501UA-CJ131T (i5-7200U/8GB/1TB/W10)' 'Inspiron 3179'
 'Notebook Odyssey' 'V320-17ISK (i3-6006U/4GB/500GB/FHD/No'
 'IdeaPad 110-15ISK' 'Latitude 5289' 'EliteBook 850' 'Aspire 1'
 'Laptop MSI' 'GS63VR 7RF' 'Tecra Z50-C-144' 'IdeaPad 310-15IKB'
 'Swift SF114-31-P5HY' 'Inspiron 7559' 'FX753VD-GC007T (i7-7700HQ/8GB/1TB'
 'GT62VR 7RE' 'CB5-132T-C9KK (N3160/4GB/32GB/Chrome' 'LifeBook A557'
 'SmartBook 140' 'Q304UA-BHI5T11 (i5-7200U/6GB/1TB/FHD/W10)' 'ZenBook 3'
 'V330-15IKB (i5-8250U/4GB/256GB/FHD/W10)' 'Ideapad 320-15ISK'
 'X541NA-GO414T (N3350/8GB/1TB/W10)' 'IdeaPad 100S-14IBR'
 '17-AK091ND (A9-9420/8GB/1TB/W10)' 'ROG GL553VE-FY022' 'Extensa EX2540'
 'Portege Z30-C-16J' 'ROG G701VI'
 'A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce' 'GL62M 7REX' 'Tecra A50-D-11M'
 'IdeaPad Y700-15ISK' 'Latitude E7470' 'Ideapad 320-15IAP'
 '15-ay047nv (i3-6006U/6GB/1TB/Radeon' 'GP72VR Leopard' 'Latitude 3580'
 '15-bs012nv (i7-7500U/8GB/1TB/Radeon' 'Tecra Z50-D-10E'
 'V310-15ISK (i5-7200U/8GB/1TB' 'Yoga 720-13IKB' 'Pavilion X360'
 'GP62 7RDX' 'Chromebook X360' 'Gram 15Z975' 'Aspire VX5-591G' 'GV62M 7RD'
 'L502NA-GO052T (N3350/4GB/128GB/W10)' 'Alienware 15' '17-bs000nv I3'
 'Yoga 730' '17-Y002nv (A10-9600P/6GB/2TB/Radeon'
 'V110-15ISK (3855U/4GB/500GB/W10)' 'Chromebook 14' 'IdeaPad 520s-14IKB'
 'TravelMate B117-M' 'Chromebook Flip' 'Portege Z30T-C-133'
 '15-bs011nv (i7-7500U/4GB/500GB/Radeon'
 'V310-15IKB (i5-7200U/4GB/1TB/FHD/W10)'
 'V310-15ISK (i3-6006U/4GB/500GB/No' 'ThinkPad P51s' 'Thinkpad T460p'
 '17-ak002nv (A10-9620P/6GB/2TB/Radeon'
 '110-15ACL (A6-7310/4GB/500GB/W10)' 'Smartbook 142'
 'V310-15IKB (i5-7200U/4GB/1TB/No' 'Inspiron 5378'
 '15-BW037na (A9-9420/4GB/1TB/Radeon' 'Predator 17'
 '15-BW091ND (A9-9420/6GB/1TB' 'Extensa EX2540-58KR'
 'V310-15IKB (i7-7500U/4GB/1TB/FHD/W10)' 'ZBook 15' 'Inspiron 7560'
 'Tecra X40-D-10G' 'Flex 5' 'Thinkpad P51s' 'Notebook 9' 'Zbook 17'
 'N23 (N3060/4GB/128GB/W10)' 'X550VX-XX015D (i5-6300HQ/4GB/1TB/GeForce'
 'Thinkpad T460' 'Pro P2540UA-XO0192R' 'Yoga 900-13ISK'
 '15-cb003na (i5-7300HQ/8GB/1TB' 'Latitude 7280' 'Zenbook UX330UA-AH5Q'
 'TravelMate P238-M' 'X751NV-TY001 (N4200/4GB/1TB/GeForce'
 'Tecra A40-C-1E5' 'EliteBook 820'
 'Q524UQ-BHI7T15 (i7-7500U/12GB/2TB/GeForce' 'Thinkpad P50' 'Vivobook Max'
 'Rog G752VS-BA171T' 'Tecra Z40-C-161' 'IdeaPad 110-15IBR' 'GS43VR 7RE'
 'GL62M (i5-7300HQ/8GB/1TB' 'Predator G9-793'
 'FX502VM-DM560T (i7-7700HQ/8GB/1TB' 'K146 (N3350/4GB/32GB/W10)'
 'Yoga 510-15IKB' 'R417NA-RS01 (N3350/4GB/32GB/W10)' 'Pro P2540UA-XS51'
 'Latitude 3180' '15-ba043na (A12-9700P/8GB/2TB/W10)' 'Omen 17-an012dx'
 'Thinkpad T470s' 'Blade Stealth' 'Latitude 3480'
 'V110-15ISK (i3-6006U/4GB/500GB/W10)' 'Tecra X40-D-10Z' 'GL62M 7RD'
 'Rog GL702VS-BA023T' 'N42-20 Chromebook'
 'R558UA-DM966T (i5-7200U/8GB/128GB/FHD/W10)' 'Rog GL702VM-GC017T'
 'ZenBook UX310UQ-GL026T' 'Rog GL502VM-DS74' 'Inspiron 5767'
 'ThinkPad T470p' 'K556UR-DM621T (i7-7500U/8GB/256GB/GeForce'
 'X541NA (N4200/4GB/1TB/W10)' 'Inspiron 5368' 'Portege X30-D-10X'
 'Portégé Z30-C-188' 'TMX349-G2-M-50FS (i5-7200U/8GB/256GB/FHD/W10)'
 'Tecra A50-D-11D' 'X541NA-GO121 (N4200/4GB/1TB/Linux)' 'Pavilion x360'
 'VivoBook L402NA' 'IdeaPad 510-15ISK' 'Rog GL753VD-GC082T'
 'Chromebook C731-C78G' 'Probook 640' 'Envy x360' 'GS73VR Stealth'
 'Portege X30-D-10V' 'G701VO-IH74K (i7-6820HK/32GB/2x' 'Gram 15Z970'
 'Chromebook CB5-571-C1DZ' 'Gram 14Z970' 'Elitebook Folio'
 'IdeaPad 510-15IKB' 'GE72VR 6RF' 'Envy 13-AB077cl' 'Tecra Z50-C-140'
 'Probook 650' 'Tecra Z40-C-12X' 'GP62M Leopard' 'Omen 17-W006na'
 'X751SV-TY001T (N3710/4GB/1TB/GeForce' 'TravelMate P259-G2'
 'Tecra A50-C-1ZV' 'Yoga 700-11ISK' 'IdeaPad Y700-15ACZ' 'Insprion 5767'
 'ZBook Studio' 'Portege Z30-C-1CW' 'ProBook x360' 'Chromebook C738T-C2EJ'
 'Portege Z30-C-16Z' 'Aspire F5-573G-510L' 'Portege X20W-D-10V'
 'Tecra A40-C-1DF' 'ThinkPad T460' '15-bs053od (i7-7500U/6GB/1TB/W10)'
 'Rog GL753VE-DS74' 'Inspiron 7579' 'Portege Z30-C-1CV' 'LifeBook A556'
 'Tecra A40-C-1KF' '15-bs005nv (i3-6006U/4GB/1TB'
 'V110-15IAP (N3350/4GB/128GB/No' 'ThinkPad T560' 'ZenBook UX310UA-FB485T'
 'Spectre 13-V111dx' 'Aspire ES1-533' 'Rog GL553VE-DS74' 'Nitro 5'
 'ENVY -' 'Portege Z30-C-16H' 'Portege A30-C-1CZ' 'ThinkPad P70'
 'Tecra Z40-C-12Z' 'Inspiron 5568' 'Portégé Z30-C-16K' 'Spectre 13-V100nv'
 'Latitude E5570' 'Tecra Z40-C-136' 'Yoga 500-15ISK'
 'V142 (X5-Z8350/2GB/32GB/W10)' 'Tecra A50-C-218' 'Thinkpad L560'
 'GT72S Dominator' 'IdeaPad Y900-17ISK' 'Chromebook C202SA' 'Noteb Pav'
 'Inspiron 5578' '250 G5' 'Aspire ES1-523' 'Inspiron 7378' 'GT62VR 6RD'
 'Rog G752VL-GC088D' 'GS63VR 6RF' 'ROG G701VO' 'Latitude 3570'
 'IdeaPad 300-17ISK' 'Ideapad 700-15ISK' 'GT72VR Dominator'
 'V110-15ISK (i5-6200U/4GB/500GB/W10)' 'Yoga 900S-12ISK' 'Chromebook 13'
 'Rog GL702VM-GC354T' 'Aspire F5-573G' 'GS70 Stealth'
 'G752VY-GC162T (i7-6700HQ/16GB/1TB' 'Latitude E5270' 'Chromebook 15'
 'GE72 Apache' '15-bw011nv (A6-9220/4GB/1TB/FHD/W10)' 'Rog GL552VW-CN470T'
 'Vostro 3559' 'V110-15ISK (i3-6006U/4GB/128GB/W10)' 'Spectre Pro'
 'Portege X30-D-10K' 'Rog GL752VW-T4308T'
 'V131 (X5-Z8350/4GB/32GB/FHD/W10)' 'Omen -'
 '15-bs078cl (i7-7500U/8GB/2TB/W10)' 'ThinkPad P40'
 'L403NA-GA013TS (N3350/4GB/32GB/W10)' 'IdeaPad 500-15ISK' 'GP62M 7RDX'
 'V110-15ISK (i3-6006U/4GB/1TB/No' '15-BA015wm (E2-7110/4GB/500GB/W10)'
 'B51-80 (i5-6200U/8GB/1TB/Radeon' '15-bw002nv (A6-9220/4GB/256GB/Radeon'
 'GP72M 7REX' 'ThinkPad T460s' 'B51-80 (i5-6200U/8GB/1008GB/Radeon'
 'GS40 Phantom' 'Pavilion 15-cb003nv' 'IdeaPad 310-15ISK' '250 G4'
 '320-15ISK (i3-6006U/4GB/1TB/GeForce' 'Stream 14-AX000nv' 'PL60 7RD'
 'X553SA-XX021T (N3050/4GB/500GB/W10)' 'V110-15ISK (i5-6200U/4GB/500GB/No'
 'UX410UA-GV097T (i3-7100U/4GB/256GB/FHD/W10)'
 'B51-80 (i7-6500U/4GB/1008GB/FHD/W7)' 'GS60 Ghost' 'Pavilion 15-BC000nv'
 'Rog GL552VW-DM201T' 'Chromebook Plus' 'Pavilion Power'
 'V110-15ISK (i3-6006U/4GB/1TB/Radeon' 'Rog G752VY-GC229T' 'GS73VR 7RF'
 'FX502VM-DM105T (i7-6700HQ/8GB/1TB/GeForce'
 '15-bs025nv (i5-7200U/8GB/256GB/W10)' 'Aspire E5-774G'
 'FX502VM-AS73 (i7-7700HQ/16GB/1TB' 'C740-C9QX (3205U/2GB/32GB/Chrome'
 'E5 774G' 'SP714-51 (i7-7Y75/8GB/256GB/FHD/W10)' 'Thinkpad T560'
 'GP62MVR 6RF' '15-bw009nv (A12-9720P/6GB/1TB/Radeon' 'Latitude E7270'
 'X540SA-RBPDN09 (N3710/4GB/1TB/W10)' 'GL62M 7RDX' 'GE72VR Apache'
 '15-bs023nv (i3-6006U/4GB/1TB/FHD/W10)' 'GL62 6QF' 'ZenBook UX310UA-WB71'
 'Inspiron 7779' 'Rog GL553VE-FY052T' 'Rog GL502VS'
 'V510-15IKB (i5-7200U/8GB/256GB/FHD/No' 'ThinkPad L460'
 'X541NA-GO020T (N3350/4GB/1TB/W10)' 'Rog G752VT-GC073T'
 'B51-80 (i7-6500U/8GB/1008GB/Radeon' 'GE62 Apache' 'Yoga 500-14IBD'
 'ZenBook UX305CA-UBM1' 'Aspire ES1-531' 'Pavilion 15-AW003nv'
 'Stream 11-Y000na' 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce'
 'Yoga 500-14ISK' '15-AC110nv (i7-6500U/6GB/1TB/Radeon'
 'X553SA-XX031T (N3050/4GB/500GB/W10)']
Column Name :  Category
Column Contents :  ['Ultrabook' 'Notebook' 'Netbook' 'Gaming' '2 in 1 Convertible'
 'Workstation']
Column Name :  Screen Size
Column Contents :  ['13.3"' '15.6"' '15.4"' '14.0"' '12.0"' '11.6"' '17.3"' '10.1"' '13.5"'
 '12.5"' '13.0"' '18.4"' '13.9"' '12.3"' '17.0"' '15.0"' '14.1"' '11.3"']
Column Name :  Screen
Column Contents :  ['IPS Panel Retina Display 2560x1600' '1440x900' 'Full HD 1920x1080'
 'IPS Panel Retina Display 2880x1800' '1366x768'
 'IPS Panel Full HD 1920x1080' 'IPS Panel Retina Display 2304x1440'
 'IPS Panel Full HD / Touchscreen 1920x1080'
 'Full HD / Touchscreen 1920x1080' 'Touchscreen / Quad HD+ 3200x1800'
 'IPS Panel Touchscreen 1920x1200' 'Touchscreen 2256x1504'
 'Quad HD+ / Touchscreen 3200x1800' 'IPS Panel 1366x768'
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160'
 'IPS Panel Full HD 2160x1440' '4K Ultra HD / Touchscreen 3840x2160'
 'Touchscreen 2560x1440' '1600x900' 'IPS Panel 4K Ultra HD 3840x2160'
 '4K Ultra HD 3840x2160' 'Touchscreen 1366x768'
 'IPS Panel Full HD 1366x768' 'IPS Panel 2560x1440'
 'IPS Panel Full HD 2560x1440' 'IPS Panel Retina Display 2736x1824'
 'Touchscreen 2400x1600' '2560x1440' 'IPS Panel Quad HD+ 2560x1440'
 'IPS Panel Quad HD+ 3200x1800'
 'IPS Panel Quad HD+ / Touchscreen 3200x1800'
 'IPS Panel Touchscreen 1366x768' '1920x1080'
 'IPS Panel Full HD 1920x1200'
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160'
 'IPS Panel Touchscreen 2560x1440' 'Touchscreen / Full HD 1920x1080'
 'Quad HD+ 3200x1800' 'Touchscreen / 4K Ultra HD 3840x2160'
 'IPS Panel Touchscreen 2400x1600']
Column Name :  CPU
Column Contents :  ['Intel Core i5 2.3GHz' 'Intel Core i5 1.8GHz'
 'Intel Core i5 7200U 2.5GHz' 'Intel Core i7 2.7GHz'
 'Intel Core i5 3.1GHz' 'AMD A9-Series 9420 3GHz' 'Intel Core i7 2.2GHz'
 'Intel Core i7 8550U 1.8GHz' 'Intel Core i5 8250U 1.6GHz'
 'Intel Core i3 6006U 2GHz' 'Intel Core i7 2.8GHz'
 'Intel Core M m3 1.2GHz' 'Intel Core i7 7500U 2.7GHz'
 'Intel Core i7 2.9GHz' 'Intel Core i3 7100U 2.4GHz'
 'Intel Atom x5-Z8350 1.44GHz' 'Intel Core i5 7300HQ 2.5GHz'
 'AMD E-Series E2-9000e 1.5GHz' 'Intel Core i5 1.6GHz'
 'Intel Core i7 8650U 1.9GHz' 'Intel Atom x5-Z8300 1.44GHz'
 'AMD E-Series E2-6110 1.5GHz' 'AMD A6-Series 9220 2.5GHz'
 'Intel Celeron Dual Core N3350 1.1GHz' 'Intel Core i3 7130U 2.7GHz'
 'Intel Core i7 7700HQ 2.8GHz' 'Intel Core i5 2.0GHz'
 'AMD Ryzen 1700 3GHz' 'Intel Pentium Quad Core N4200 1.1GHz'
 'Intel Atom x5-Z8550 1.44GHz' 'Intel Celeron Dual Core N3060 1.6GHz'
 'Intel Core i5 1.3GHz' 'AMD FX 9830P 3GHz' 'Intel Core i7 7560U 2.4GHz'
 'AMD E-Series 6110 1.5GHz' 'Intel Core i5 6200U 2.3GHz'
 'Intel Core M 6Y75 1.2GHz' 'Intel Core i5 7500U 2.7GHz'
 'Intel Core i3 6006U 2.2GHz' 'AMD A6-Series 9220 2.9GHz'
 'Intel Core i7 6920HQ 2.9GHz' 'Intel Core i5 7Y54 1.2GHz'
 'Intel Core i7 7820HK 2.9GHz' 'Intel Xeon E3-1505M V6 3GHz'
 'Intel Core i7 6500U 2.5GHz' 'AMD E-Series 9000e 1.5GHz'
 'AMD A10-Series A10-9620P 2.5GHz' 'AMD A6-Series A6-9220 2.5GHz'
 'Intel Core i5 2.9GHz' 'Intel Core i7 6600U 2.6GHz'
 'Intel Core i3 6006U 2.0GHz' 'Intel Celeron Dual Core 3205U 1.5GHz'
 'Intel Core i7 7820HQ 2.9GHz' 'AMD A10-Series 9600P 2.4GHz'
 'Intel Core i7 7600U 2.8GHz' 'AMD A8-Series 7410 2.2GHz'
 'Intel Celeron Dual Core 3855U 1.6GHz'
 'Intel Pentium Quad Core N3710 1.6GHz' 'AMD A12-Series 9720P 2.7GHz'
 'Intel Core i5 7300U 2.6GHz' 'AMD A12-Series 9720P 3.6GHz'
 'Intel Celeron Quad Core N3450 1.1GHz'
 'Intel Celeron Dual Core N3060 1.60GHz' 'Intel Core i5 6440HQ 2.6GHz'
 'Intel Core i7 6820HQ 2.7GHz' 'AMD Ryzen 1600 3.2GHz'
 'Intel Core i7 7Y75 1.3GHz' 'Intel Core i5 7440HQ 2.8GHz'
 'Intel Core i7 7660U 2.5GHz' 'Intel Core i7 7700HQ 2.7GHz'
 'Intel Core M m3-7Y30 2.2GHz' 'Intel Core i5 7Y57 1.2GHz'
 'Intel Core i7 6700HQ 2.6GHz' 'Intel Core i3 6100U 2.3GHz'
 'AMD A10-Series 9620P 2.5GHz' 'AMD E-Series 7110 1.8GHz'
 'Intel Celeron Dual Core N3350 2.0GHz' 'AMD A9-Series A9-9420 3GHz'
 'Intel Core i7 6820HK 2.7GHz' 'Intel Core M 7Y30 1.0GHz'
 'Intel Xeon E3-1535M v6 3.1GHz' 'Intel Celeron Quad Core N3160 1.6GHz'
 'Intel Core i5 6300U 2.4GHz' 'Intel Core i3 6100U 2.1GHz'
 'AMD E-Series E2-9000 2.2GHz' 'Intel Celeron Dual Core N3050 1.6GHz'
 'Intel Core M M3-6Y30 0.9GHz' 'AMD A9-Series 9420 2.9GHz'
 'Intel Core i5 6300HQ 2.3GHz' 'AMD A6-Series 7310 2GHz'
 'Intel Atom Z8350 1.92GHz' 'Intel Xeon E3-1535M v5 2.9GHz'
 'Intel Core i5 6260U 1.8GHz' 'Intel Pentium Dual Core N4200 1.1GHz'
 'Intel Celeron Quad Core N3710 1.6GHz' 'Intel Core M 1.2GHz'
 'AMD A12-Series 9700P 2.5GHz' 'Intel Core i7 7500U 2.5GHz'
 'Intel Pentium Dual Core 4405U 2.1GHz' 'AMD A4-Series 7210 2.2GHz'
 'Intel Core i7 6560U 2.2GHz' 'Intel Core M m7-6Y75 1.2GHz'
 'AMD FX 8800P 2.1GHz' 'Intel Core M M7-6Y75 1.2GHz'
 'Intel Core i5 7200U 2.50GHz' 'Intel Core i5 7200U 2.70GHz'
 'Intel Atom X5-Z8350 1.44GHz' 'Intel Core i5 7200U 2.7GHz'
 'Intel Core M 1.1GHz' 'Intel Pentium Dual Core 4405Y 1.5GHz'
 'Intel Pentium Quad Core N3700 1.6GHz' 'Intel Core M 6Y54 1.1GHz'
 'Intel Core i7 6500U 2.50GHz' 'Intel Celeron Dual Core N3350 2GHz'
 'Samsung Cortex A72&A53 2.0GHz' 'AMD E-Series 9000 2.2GHz'
 'Intel Core M 6Y30 0.9GHz' 'AMD A9-Series 9410 2.9GHz']
Column Name :  RAM
Column Contents :  ['8GB' '16GB' '4GB' '2GB' '12GB' '6GB' '32GB' '24GB' '64GB']
Column Name :   Storage
Column Contents :  ['128GB SSD' '128GB Flash Storage' '256GB SSD' '512GB SSD' '500GB HDD'
 '256GB Flash Storage' '1TB HDD' '32GB Flash Storage'
 '128GB SSD +  1TB HDD' '256GB SSD +  256GB SSD' '64GB Flash Storage'
 '256GB SSD +  1TB HDD' '256GB SSD +  2TB HDD' '32GB SSD' '2TB HDD'
 '64GB SSD' '1TB Hybrid' '512GB SSD +  1TB HDD' '1TB SSD'
 '256GB SSD +  500GB HDD' '128GB SSD +  2TB HDD' '512GB SSD +  512GB SSD'
 '16GB SSD' '16GB Flash Storage' '512GB SSD +  256GB SSD'
 '512GB SSD +  2TB HDD' '64GB Flash Storage +  1TB HDD' '1GB SSD'
 '1TB HDD +  1TB HDD' '32GB HDD' '1TB SSD +  1TB HDD'

In [15]:
df.dtypes

Manufacturer         object
Model Name           object
Category             object
Screen Size          object
Screen               object
CPU                  object
RAM                  object
 Storage             object
GPU                  object
Operating System     object
Weight               object
Price               float64
dtype: object

In [ ]:
model_name = df['Model Name'].unique()
model_name.sort()
model_name

In [ ]:
df[['Model Name','CPU']]

In [ ]:
df['Model Name'].str.contains('/')

In [ ]:
print('Yoga' in df['Model Name'].unique())

In [ ]:
df[df['Model Name'].str.contains('/')]

In [ ]:
category = df['Category'].unique()
category.sort()
category

In [ ]:
# gives a tuple of column name and series
# for each column in the dataframe
for (columnName, columnData) in df.items():
    print('Column Name : ', columnName)
    print('Column Contents : ', columnData.nunique())

In [ ]:
screen_size = df['Screen Size'].unique()
screen_size.sort()
screen_size

In [ ]:
screen = df['Screen'].unique()
screen.sort()
print(df['Screen'].value_counts())
screen

In [ ]:
CPU = df['CPU'].unique()
CPU.sort()
print(df['CPU'].value_counts())
CPU

In [ ]:
RAM = df['RAM'].unique()
RAM.sort()
print(df['RAM'].value_counts())
RAM

In [ ]:
storage = df[' Storage'].unique()
storage.sort()
print(df[' Storage'].value_counts())
storage

In [ ]:
GPU = df['GPU'].unique()
GPU.sort()
print(df['GPU'].value_counts())
GPU

In [ ]:
OS = df['Operating System'].unique()
OS.sort()
print(df['Operating System'].value_counts())
OS

In [ ]:
weight = df['Weight'].unique()
weight.sort()
print(df['Weight'].value_counts())
weight

In [ ]:
price = df['Price'].unique()
price.sort()
print(df['Price'].value_counts())
price

In [ ]:
df.columns

In [ ]:
#1 INR = 0.012203 USD Conversion Rate as of May 10,2023
df['Price_USD'] = df.Price/81.9433
df.Price_USD

In [ ]:
df[['Price','Price_USD']]

In [ ]:
#Target Encoding for Manfacturer

In [ ]:
df['Weight_LBS'] = df.Weight*2.204623
df.Weight_LBS

In [ ]:
df.Weight = df.Weight.str.replace('kg','')

In [ ]:
df.Weight = df.Weight.astype(float)

In [ ]:
#4s is a typo. Google search the weight of the laptop
df.Weight = df.Weight.replace('4s','4.04')

In [ ]:
df[['Weight','Weight_LBS']]

In [ ]:
#Operating System Typo
df['Operating System'] = df['Operating System'].replace('macOS','Mac OS')

In [ ]:
df['RAM']

In [ ]:
#Clearing GB from string and converting to int
df.RAM = df.RAM.str.replace('GB','')
df.RAM = df.RAM.astype(int)

In [ ]:
df.info()

In [ ]:
#Remove Leading Space in Column Name
df.rename(columns = {' Storage':'Storage'}, inplace = True)

In [ ]:
df['Screen Size']

In [ ]:
#Clearing " from string and converting to float
df['Screen Size'] = df['Screen Size'].str.replace('"','')
df['Screen Size'] = df['Screen Size'].astype(float)

In [ ]:
df.info()

In [ ]:
""" Pattern of the CPU string Brand, Model Number, and Speed
Since the brand and model number vary in length
The string will be flipped to take the Speed then
take the brand from the front of the string """
CPU_df = df[['CPU']].copy()
# Python code
# To reverse words in a given string
CPU_reversed = []
# input string
for x in CPU_df.CPU:
    # reversing words in a given string
    s = x.split()[::-1]
    l = []
    for i in s:
        # appending reversed words to l
        l.append(i)
    # printing reverse words
    CPU_reversed.append(" ".join(l))

In [ ]:
#Creating New feature - CPU Speed
CPU_df['CPU_reversed'] = CPU_reversed
new = CPU_df['CPU_reversed'].str.split(' ', expand=True, n=2)
df['CPU_Speed'] = new[0]
df['CPU_Speed'] = df['CPU_Speed'].str.replace('GHz','')
df['CPU_Speed'] = df['CPU_Speed'].astype(float)
new['CPU_Flipped'] = new[1] + " " +new[2]

In [ ]:
# Python code
# To reverse words in a given string
CPU_flipped = []
# input string
for x in new.CPU_Flipped:
    # reversing words in a given string
    s = x.split()[::-1]
    l = []
    for i in s:
        # appending reversed words to l
        l.append(i)
    # printing reverse words
    CPU_flipped.append(" ".join(l))

In [ ]:
#Creating New features - CPU Brand and Model
new['CPU_flipped'] = CPU_flipped
new2 = new['CPU_flipped'].str.split(' ', expand=True, n=1)
df['CPU Brand'] = new2[0]
df['CPU Model'] = new2[1]

In [ ]:
#Exploring new features
CPU_speed = df['CPU_Speed'].unique()
CPU_speed.sort()
print(df['CPU_Speed'].value_counts())
CPU_speed

In [ ]:
df.info()

In [ ]:
#Exploring new features
CPU_brand = df['CPU Brand'].unique()
CPU_brand.sort()
print(df['CPU Brand'].value_counts())
CPU_brand

In [ ]:
#Exploring new features
CPU_model = df['CPU Model'].unique()
CPU_model.sort()
print(df['CPU Model'].value_counts())
CPU_model

In [ ]:
#Creating new features - GPU Brand and Model from GPU
new3 = df['GPU'].str.split(' ', expand=True, n=1)
df['GPU Brand'] = new3[0]
df['GPU Model'] = new3[1]

In [ ]:
GPU_model = df['GPU Model'].unique()
GPU_model.sort()
print(df['GPU Model'].value_counts())
GPU_model

In [ ]:
GPU_brand = df['GPU Brand'].unique()
GPU_brand.sort()
print(df['GPU Brand'].value_counts())
GPU_brand

In [ ]:
#Some of the Model Names had redundant information captured in other columns
new4 = df['Model Name'].str.split('(', expand=True, n=1)
df['Model Name Cleaned'] = new4[0]

In [ ]:
model_name_c = df['Model Name Cleaned'].unique()
model_name_c.sort()
print(df['Model Name Cleaned'].value_counts())
model_name_c

In [ ]:
#Creating new feature of whether the screen is touchscreen
screen_touch = []

for x in df.Screen:
    if 'Touchscreen' in x:
        screen_touch.append(1)
    else:
        screen_touch.append(0)

In [ ]:
#Creating new feature of whether the screen is hd
screen_hd = []

for x in df.Screen:
    if 'HD' in x:
        screen_hd.append(1)
    else:
        screen_hd.append(0)

In [ ]:
df['Touchscreen'] = screen_touch
df['Screen_HD'] = screen_hd

In [ ]:
new5 = df['Screen'].str.split(' ', expand=True)
new5 = new5.fillna('0')

In [ ]:
#Creating new feature - screen quality from Screen column
screen_quality = []
for index,row in new5.iterrows():
    screen_quality.append(row[row.str.contains('x')].values[0])
 #       screen_quality.append(row[index])
  #  else:
   #     screen_quality.append(0)

In [ ]:
df['Screen Quality'] = screen_quality

In [ ]:
screen_quality_cleaned = df['Screen Quality'].unique()
screen_quality_cleaned.sort()
print(df['Screen Quality'].value_counts())
screen_quality_cleaned

In [ ]:
df.Screen

In [ ]:
""" Certain rows have multiple storage types and sizes.
Combining multiple storage types into total storage in the TB units """
new6 = df['Storage'].str.split(' ', expand=True)
storage = []
for index,row in new6.iterrows():
    storage.append(row[row.str.contains('B')].values)
new6 = new6.fillna('0')

In [ ]:
storage_df = pd.DataFrame(storage)

In [ ]:
storage_df = storage_df.fillna('0GB')

In [ ]:
#*(1024*1024*1024)
#*(1024*1024*1024*1024)
col_0 = []
for val in storage_df[0]:
    if 'GB' in val:
        col_0.append(int(re.findall(r'\d+',val)[0])*(1024*1024*1024))
    elif 'TB' in val:
        col_0.append(int(re.findall(r'\d+',val)[0])*(1024*1024*1024*1024))
    else:
        print('Nothing')

In [ ]:
col_1 = []
for val in storage_df[1]:
    if 'GB' in val:
        col_1.append(int(re.findall(r'\d+',val)[0])*(1024*1024*1024))
    elif 'TB' in val:
        col_1.append(int(re.findall(r'\d+',val)[0])*(1024*1024*1024*1024))
    else:
        print('Nothing')

In [ ]:
res_list = [col_0[i] + col_1[i] for i in range(len(col_0))]
total_storage_list = [x/(1024*1024*1024*1024) for x in res_list]
df['Total Storage in TB'] = total_storage_list

In [ ]:
df[['Storage','Total Storage in TB']]

In [ ]:
df.to_csv('datasets/laptops_preprocessed.csv',index=True)

In [ ]:
df = pd.read_csv('datasets/laptops_preprocessed.csv',index_col=0)
df.head()

,Manufacturer,Model Name,Model Name Cleaned,Category,Screen Size,Screen,Touchscreen,Screen_HD,Screen Quality,CPU,...,Storage,Total Storage in TB,GPU,GPU Brand,GPU Model,Operating System,Weight,Weight_LBS,Price,Price_USD
0,Apple,MacBook Pro,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,0,0,2560x1600,Intel Core i5 2.3GHz,...,128GB SSD,0.125,Intel Iris Plus Graphics 640,Intel,Iris Plus Graphics 640,Mac OS,1.37,3.020334,11912523.48,145375.19820
1,Apple,Macbook Air,Macbook Air,Ultrabook,13.3,1440x900,0,0,1440x900,Intel Core i5 1.8GHz,...,128GB Flash Storage,0.125,Intel HD Graphics 6000,Intel,HD Graphics 6000,Mac OS,1.34,2.954195,7993374.48,97547.62720
2,HP,250 G6,250 G6,Notebook,15.6,Full HD 1920x1080,0,1,1920x1080,Intel Core i5 7200U 2.5GHz,...,256GB SSD,0.250,Intel HD Graphics 620,Intel,HD Graphics 620,No OS,1.86,4.100599,5112900.00,62395.58329
3,Apple,MacBook Pro,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,0,0,2880x1800,Intel Core i7 2.7GHz,...,512GB SSD,0.500,AMD Radeon Pro 455,AMD,Radeon Pro 455,Mac OS,1.83,4.034460,22563005.40,275348.99620
4,Apple,MacBook Pro,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,0,0,2560x1600,Intel Core i5 3.1GHz,...,256GB SSD,0.250,Intel Iris Plus Graphics 650,Intel,Iris Plus Graphics 650,Mac OS,1.37,3.020334,16037611.20,195715.95480

In [ ]:
#apply(lambda x: int(x.split(' ')[0]))
#Example of cleaner way to create new features

In [ ]:
objList = df.select_dtypes(include = "object").columns
print (objList)

Index(['Manufacturer', 'Model Name', 'Model Name Cleaned', 'Category',
       'Screen', 'Screen Quality', 'CPU', 'CPU Brand', 'CPU Model', 'Storage',
       'GPU', 'GPU Brand', 'GPU Model', 'Operating System'],
      dtype='object')

In [ ]:
#Label Encoding for object to numeric conversion
le = LabelEncoder()

for feat in objList:
    df[feat] = le.fit_transform(df[feat].astype(str))

print (df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1302 entries, 0 to 1301
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         1302 non-null   int32
 1   Model Name           1302 non-null   int32
 2   Model Name Cleaned   1302 non-null   int32
 3   Category             1302 non-null   int32
 4   Screen Size          1302 non-null   float64
 5   Screen               1302 non-null   int32
 6   Touchscreen          1302 non-null   int64
 7   Screen_HD            1302 non-null   int64
 8   Screen Quality       1302 non-null   int32
 9   CPU                  1302 non-null   int32
 10  CPU Brand            1302 non-null   int32
 11  CPU Model            1302 non-null   int32
 12  CPU_Speed            1302 non-null   float64
 13  RAM                  1302 non-null   int64
 14  Storage              1302 non-null   int32
 15  Total Storage in TB  1302 non-null   float64
 16  GPU                  1302 non-null   int32
 17  GPU Brand            1302 non-null   int32
 18  GPU Model            1302 non-null   int32
 19  Operating System     1302 non-null   int32
 20  Weight               1302 non-null   float64
 21  Weight_LBS           1302 non-null   float64
 22  Price                1302 non-null   float64
 23  Price_USD            1302 non-null   float64
dtypes: float64(7), int32(14), int64(3)
memory usage: 183.1 KB
None

In [ ]:
#Saving df after LabelEncoder is applied
df.to_csv('datasets/laptops_afterlabelencoder.csv',index=True)

## Normality Test<a id="stats"></a>

## Splitting Data<a id="train_split"></a>

In [ ]:
#Choosing the features to be used in the model
X = df.drop(['Model Name','Screen','CPU','Storage','GPU','Weight','Price','Price_USD'],axis='columns')

In [ ]:
#Choosing target for the model
y = df.Price_USD
y.head()

0    145375.19820
1     97547.62720
2     62395.58329
3    275348.99620
4    195715.95480
Name: Price_USD, dtype: float64

In [ ]:
#Splitting train and test data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=43)

## Setting Model<a id="set"></a>

In [ ]:
#Deciding on best model for the data

regressors = [
    KNeighborsRegressor(),
    GradientBoostingRegressor(),
    KNeighborsRegressor(),
    ExtraTreesRegressor(),
    RandomForestRegressor(),
    DecisionTreeRegressor(),
    LinearRegression(),
    Lasso(),
    Ridge()
]

cv = ShuffleSplit(n_splits=5,test_size=0.2, random_state=0)
head = 10
for model in regressors[:head]:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test) 
    print(model)
    print("\tExplained variance:", explained_variance_score(y_test, y_pred))
    print("\tMean absolute error:", mean_absolute_error(y_test, y_pred))
    print("\tR2 score:", r2_score(y_test, y_pred))
    print(cross_val_score(model,X,y,cv=cv))
    print()

KNeighborsRegressor()
	Training time: 0.002s
	Prediction time: 0.017s
	Explained variance: 0.7456339753457355
	Mean absolute error: 25379.263703348657
	R2 score: 0.7446258061416231

GradientBoostingRegressor()
	Training time: 0.158s
	Prediction time: 0.002s
	Explained variance: 0.8831144798210268
	Mean absolute error: 18919.316523457474
	R2 score: 0.8790154524455557

KNeighborsRegressor()
	Training time: 0.001s
	Prediction time: 0.012s
	Explained variance: 0.7456339753457355
	Mean absolute error: 25379.263703348657
	R2 score: 0.7446258061416231

ExtraTreesRegressor()
	Training time: 0.352s
	Prediction time: 0.012s
	Explained variance: 0.9031180342930277
	Mean absolute error: 16219.557399392028
	R2 score: 0.9005268273155099

RandomForestRegressor()
	Training time: 0.539s
	Prediction time: 0.015s
	Explained variance: 0.8868551479248608
	Mean absolute error: 16854.727187884182
	R2 score: 0.8856871244724549

DecisionTreeRegressor()
	Training time: 0.008s
	Prediction time: 0.002s
	Explained variance: 0.826685961856734
	Mean absolute error: 21839.547603716474
	R2 score: 0.826629537135732

LinearRegression()
	Training time: 0.005s
	Prediction time: 0.001s
	Explained variance: 0.725560267230712
	Mean absolute error: 30155.814294576954
	R2 score: 0.7217659728141248

Lasso()
	Training time: 0.006s
	Prediction time: 0.002s
	Explained variance: 0.7255604589885247
	Mean absolute error: 30155.72565182683
	R2 score: 0.7217660657129893

Ridge()
	Training time: 0.003s
	Prediction time: 0.001s
	Explained variance: 0.7256285639323394
	Mean absolute error: 30148.174656189418
	R2 score: 0.7218344104344818

## Training Model<a id="training"></a>

In [ ]:
#Hyperparameter tuning for GradientBoostingRegressor()
parameters = {'learning_rate': [0.01,0.02,0.03,0.04],
                  'subsample'    : [0.9, 0.5, 0.2, 0.1],
                  'n_estimators' : [100,500,1000, 1500],
                  'max_depth'    : [4,6,8,10]
                 }

grid_GBR = GridSearchCV(estimator=GradientBoostingRegressor(), param_grid = parameters, cv = 2, n_jobs=-1)
grid_GBR.fit(X_train, y_train)

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

In [ ]:
#Hyperparameter tuning for ExtraTreesRegressor()
param_grid = {
    'n_estimators': [10,50,100],
    'criterion': ['mse', 'mae'],
    'max_depth': [2,8,16,32,50],
    'min_samples_split': [2,4,6],
    'min_samples_leaf': [1,2],
    #'oob_score': [True, False],
    'max_features': ['auto','sqrt','log2'],    
    'bootstrap': [True, False],
    'warm_start': [True, False],
}

model = ExtraTreesRegressor ()

gcv = GridSearchCV(model,param_grid,cv=5,n_jobs=-1).fit(X_train,y_train)
print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",gcv.best_estimator_)
print("\n The best score across ALL searched params:\n",gcv.best_score_)
print("\n The best parameters across ALL searched params:\n",gcv.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 ExtraTreesRegressor(criterion='mse', max_depth=50, max_features='sqrt',
                    min_samples_split=4, n_estimators=50, warm_start=True)

 The best score across ALL searched params:
 0.8254279245091919

 The best parameters across ALL searched params:
 {'bootstrap': False, 'criterion': 'mse', 'max_depth': 50, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 50, 'warm_start': True}

c:\Users\hinso\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

In [ ]:
#Hyperparameter tuning for RandomForestRegressor()
rfc=RandomForestRegressor(random_state=42)

param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['squared_error', 'absolute_error', 'friedman_mse', 'poisson']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X_train, y_train)

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",CV_rfc.best_estimator_)
print("\n The best score across ALL searched params:\n",CV_rfc.best_score_)
print("\n The best parameters across ALL searched params:\n",CV_rfc.best_params_)

In [ ]:
#Hyperparameter tuning for DecisionTreeRegressor()

parameters={"splitter":["best","random"],
            "max_depth" : [1,3,5,7,9,11,12],
           "min_samples_leaf":[1,2,3,4,5,6,7,8,9,10],
           "min_weight_fraction_leaf":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
           "max_features":["auto","log2","sqrt",None],
           "max_leaf_nodes":[None,10,20,30,40,50,60,70,80,90] }

tuning_model=GridSearchCV(DecisionTreeRegressor(),param_grid=parameters,scoring='neg_mean_squared_error',cv=3,verbose=3)
tuning_model.fit(X_train,y_train)

print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",tuning_model.best_estimator_)
print("\n The best score across ALL searched params:\n",tuning_model.best_score_)
print("\n The best parameters across ALL searched params:\n",tuning_model.best_params_)

In [ ]:
#Checking scores of the hyperparameter tuned models
regressors = [
    ExtraTreesRegressor(criterion='mse', max_depth=50, max_features='sqrt',
                    min_samples_split=4, n_estimators=50, warm_start=True),
    RandomForestRegressor(max_depth=8, max_features='sqrt', n_estimators=200,
                      random_state=42)
]

head = 2
for model in regressors[:head]:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test) 
    print(model)
    print("\tExplained variance:", explained_variance_score(y_test, y_pred))
    print("\tMean absolute error:", mean_absolute_error(y_test, y_pred))
    print("\tR2 score:", r2_score(y_test, y_pred))
    print(cross_val_score(model,X,y,cv=cv))
    print()

c:\Users\hinso\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

ExtraTreesRegressor(criterion='mse', max_depth=50, max_features='sqrt',
                    min_samples_split=4, n_estimators=50, warm_start=True)
	Training time: 0.082s
	Prediction time: 0.007s
	Explained variance: 0.8919367898716148
	Mean absolute error: 16665.30493547048
	R2 score: 0.8890409259834438

RandomForestRegressor(max_depth=8, max_features='sqrt', n_estimators=200,
                      random_state=42)
	Training time: 0.300s
	Prediction time: 0.016s
	Explained variance: 0.8486892426386257
	Mean absolute error: 19978.59634288556
	R2 score: 0.8450947501712552

## Best Results<a id="compare_results"></a>

In [ ]:
#Final model and score
best_model = ExtraTreesRegressor(criterion='mse', max_depth=50, max_features='sqrt',
                    min_samples_split=4, n_estimators=50, warm_start=True)

best_model.fit(X_train,y_train)
best_model.score(X_test,y_test)

c:\Users\hinso\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_forest.py:400: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(

0.8815112581250318

## Finalizing Workflow<a id="workflow"></a>

## Fitting the final model<a id="fit"></a>

## Interface(Streamlit)<a id="interface"></a>

## Saving Files<a id="store"></a>

In [ ]:
#Saving the model
with open('laptop_price_regression.pickle','wb') as f:
    pickle.dump(best_model,f)

In [ ]:
#Saving Column names
columns={
    'data_columns': [col.lower() for col in X.columns]
}

with open('columns.json','w') as f:
    f.write(json.dumps(columns))

In [ ]:
#Storing LabelEncoder for GUI use
filehandler = open("le.obj","wb")
pickle.dump(le,filehandler)
filehandler.close()

In [ ]:
#Saving unique column values for GUI drop down fields
dict = {}

for (columnName, columnData) in df.items():
    #print('Column Name : ', columnName)
    #print('Column Contents : ', columnData.unique())
    dict[columnName] = columnData.unique().tolist()

with open("column_values.json", "w") as outfile:
    json.dump(dict, outfile)

Column Name :  Manufacturer
Column Name :  Model Name
Column Name :  Model Name Cleaned
Column Name :  Category
Column Name :  Screen Size
Column Name :  Screen
Column Name :  Touchscreen
Column Name :  Screen_HD
Column Name :  Screen Quality
Column Name :  CPU
Column Name :  CPU Brand
Column Name :  CPU Model
Column Name :  CPU_Speed
Column Name :  RAM
Column Name :  Storage
Column Name :  Total Storage in TB
Column Name :  GPU
Column Name :  GPU Brand
Column Name :  GPU Model
Column Name :  Operating System
Column Name :  Weight
Column Name :  Weight_LBS
Column Name :  Price
Column Name :  Price_USD

C:\Users\hinso\AppData\Local\Temp\ipykernel_5104\3705546538.py:3: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for (columnName, columnData) in df.iteritems():

## Conclusion<a id="conclusion"></a>